inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.0

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
